### ISSUE TITLE
Intro to Learn - Ask a Question

### ISSUE THREAD

**Issue by RoyEriksen** [learn-co-curriculum/ask-a-question#2]
On the Ask a Question portion of the introduction the "Ask a Question" button does not appear at the top right hand corner of the page. 
![ask a question screen shot](https://cloud.githubusercontent.com/assets/16513707/12073939/5f790a06-b174-11e5-9d64-a8e2b3ea9e35.png)

**Comment by AnnJohn** [comment]
Hi @RoyEriksen this is working fine on our end, but it could be a bug. If this problem is still the case, could you please file a bug report? If you hover over your profile pic in Learn you'll see an option to Report a Bug. Thanks!
