### ISSUE TITLE
Ask a questtion button not working

### ISSUE THREAD

**Issue by rgo8** [learn-co-curriculum/ask-a-question#3]
Clicked on Ask a question feature but did not see a text field where I could type a question. Tried Chrome and Safari on a MacBook Pro (El Capitan v.10.11.4). "Completed" lesson without asking a question...Suggestions and feedback welcomed.

**Comment by AnnJohn** [comment]
hi @rgo8 sorry for the delay, but it should be working now. thanks. 

if in the future, the ask a question button doesn't work, could you please file a bug report instead? if you hover over you profile pic in Learn, you'll see a menu with the option to file a bug report. thanks!
